version: '3'
networks:
  graphql:
services:
  app:
    build: .
    container_name: app
    networks:
      - graphql
  web:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    networks:
      - graphql
